# Generated by Django 6.1 on 2026-08-31 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('logo_initial', models.CharField(default='CO', max_length=4)),
                ('tech_stack', models.CharField(help_text='Comma separated, e.g. Java, Spring Boot, AWS', max_length=300)),
                ('industry', models.CharField(default='IT Services', max_length=120)),
                ('interview_style_tags', models.CharField(help_text='Comma separated tags e.g. DSA-heavy, culture-fit-heavy, case-study-based', max_length=300)),
                ('rounds_config', models.TextField(help_text='Describe the rounds this company typically runs, one per line.')),
                ('tone_description', models.TextField(help_text="How this company's interviewers typically speak/behave, used in AI system prompts.")),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('current_persona', models.CharField(default='technical', max_length=20)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_type', models.CharField(choices=[('technical', 'Technical Interviewer'), ('hr', 'HR Interviewer'), ('manager', 'Panel Manager')], max_length=20)),
                ('display_name', models.CharField(max_length=80)),
                ('system_prompt_template', models.TextField(help_text='Prompt template. Use {company}, {tech_stack}, {tone}, {tags} as placeholders.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_type', models.CharField(max_length=20)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('response_time_seconds', models.FloatField(default=0)),
                ('sentiment_score', models.FloatField(default=0)),
                ('confidence_score', models.FloatField(default=0)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='SessionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.FloatField(default=0)),
                ('hr_score', models.FloatField(default=0)),
                ('confidence_score', models.FloatField(default=0)),
                ('fit_score', models.FloatField(default=0)),
                ('weak_areas', models.CharField(blank=True, max_length=300)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='core.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(blank=True, help_text='Comma separated skills', max_length=400)),
                ('target_role', models.CharField(blank=True, default='Software Developer', max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
